cleanup: drop certs
ExodusMovement/hedera-sdk-js pull request #59
Opened 2021-12-15 20:42 UTC by ChALkeR

They are not useful in the current impl, the removed `setCert` function was never called.

`setCert` exists in `Node` and `ManagedNode`.
In `Node`, it does something, in `ManagedNode` it's a noop (just `return this`).

But the only place where it's called is `src/client/ManagedNetwork.js` (method `setTransportSecurity`):
```js
           for (let i = 0; i < this._nodes.length; i++) {
                let node = this._nodes[i];
                node.close();

                node = /** @type {NetworkNodeT} */ (
                    transportSecurity
                        ? node
                              .toSecure()
                              .setCert(
                                  this._ledgerId != null ? this._ledgerId : ""
                              )
                        : node.toInsecure()
                );
```
And there it happens on entries from `this._nodes`.
But `this._nodes` is an array of `ManagedNode` instances: `* @template {ManagedNode<ChannelT>} NetworkNodeT`.
So there `setCert()` is a noop.

I'll file an upstream report, but let's just remove this unneeded code from the fork to minimize the bundle.

2021-12-23 07:46 UTC, feri42 approved these changes
tACK - tests pass in `hedera-api/lib` including sending a trasnaction.

2021-12-23 08:58 UTC, feri42 requested changes
nACK - verified that this breaks server-side:
```
"Error: (BUG) keyToProtobuf: unsupported key type: PublicKey\n    at keyToProtobuf (/home/feri/Work/Exodus/Hedera/hedera-account-faucet/node_modules/@exodus/hashgraph-sdk/lib/cryptography/protobuf.cjs:49:9)\n    at AccountCreateTransaction._makeTransactionData (/home/feri/Work/Exodus/Hedera/hedera-account-faucet/node_modules/@exodus/hashgraph-sdk/lib/account/AccountCreateTransaction.cjs:175:60)\n    at AccountCreateTransaction._makeTransactionBody (/home/feri/Work/Exodus/Hedera/hedera-account-faucet/node_modules/@exodus/hashgraph-sdk/lib/transaction/Transaction.cjs:632:46)\n    at AccountCreateTransaction._makeSignedTransaction (/home/feri/Work/Exodus/Hedera/hedera-account-faucet/node_modules/@exodus/hashgraph-sdk/lib/transaction/Transaction.cjs:618:23)\n    at /home/feri/Work/Exodus/Hedera/hedera-account-faucet/node_modules/@exodus/hashgraph-sdk/lib/transaction/Transaction.cjs:410:65\n    at Array.map (<anonymous>)\n    at AccountCreateTransaction.freezeWith (/home/feri/Work/Exodus/Hedera/hedera-account-faucet/node_modules/@exodus/hashgraph-sdk/lib/transaction/Transaction.cjs:410:46)\n    at AccountCreateTransaction.freeze (/home/feri/Work/Exodus/Hedera/hedera-account-faucet/node_modules/@exodus/hashgraph-sdk/lib/transaction/Transaction.cjs:374:17)\n    at buildTx (/home/feri/Work/Exodus/Hedera/hedera-account-faucet/packages/hedera-account-faucet/lib/node_modules/@exodus/hedera-lib/src/prepare-tx.js:27:20)\n    at HederaAccountFaucet.createAccount (/home/feri/Work/Exodus/Hedera/hedera-account-faucet/packages/hedera-account-faucet/lib/hedera-faucet.js:199:41)","error":{}}}
```
The error doesn't seem to be cert related though. Not sure if I did something else wrong. But I did verify that I only had one instance of `@exodus/hashgraph-sdk` and that it was the modified instance.

2025-04-26 14:13 UTC, ChALkeR commented
@feri42 that error looks like a failed `instanceof` check likely because you have two versions of some lib (either sdk, cryptography or proto)

2025-04-26 14:23 UTC, ChALkeR commented
The only think which was affected by this was `NodeChannel` which is already deleted
So this is just dead code, that param is not used in any of the two existing channels.

2025-04-27 04:03 UTC, ChALkeR commented
Will just land and revert if it breaks smth

2025-04-27 04:06 UTC, merged